name: 'nifty500_stock_pipeline'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nifty500_stock_pipeline:
    staging:
      +schema: nifty500_silver
      +materialized: view
    silver:
      +schema: nifty500_silver
      +materialized: table
    gold:
      +schema: nifty500_gold
      +materialized: table
